spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: none
      format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

elasticsearch:
  hosts: http://20.194.1.89:9200

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
