spring:
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    url: jdbc:oracle:thin:@20.194.16.231:49161:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: dev_user
    password: dev_user
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
#      ddl-auto: none
      format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE

elasticsearch:
  hosts: http://20.194.41.183:9200

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8088

search:
  index: metricbeat-*
  field:
    id: host.id
    cpu: system.cpu
    mem: system.memory
  include:
    cpu: system.cpu.total
    mem: system.memory.total,system.memory.used,system.memory.free
  range:
    field: "@timestamp"
    gte: now-10h/h
    lte: now
  sort: "@timestamp"